### ISSUE TITLE
History Fetching

### ISSUE THREAD

**Issue by dengboren86** [eosrio/Hyperion-History-API#18]
Dear Hyperion developers,

Is Hyperion an api to fetch history data from your server,
or users need to sync mainnet blocks locally?

If the latter is true, how long may it take to sync all info, and how large it is expected to be?

Thank you!
Boren

**Comment by matthewdarwin** [comment]
Hello Boren,

In order to use hyperion, you need to have a nodeos instance running with state history enabled.  Either you can run that locally yourself (recommended) or ask someone to share their state history with you (probably nobody is going to do that for free).  Once you have state history ready, then you can integrate it into hyperion.

You can download a state history snapshot to get started so you don't have to sync from scratch https://snapshots.eosamsterdam.net/

An EOS Mainnet node with full state history takes 1.5TB disk space as of now.  Add hyperion on top of that.

Also better place for this kind of question is the Hyperion telegram channel https://t.me/EOSHyperion, rather than opening a github issue.

**Comment by dengboren86** [comment]
Well noted. Thank you so much for the info. It perfectly answers.

**Comment by igorls** [comment]
Great answers @matthewdarwin thanks
